name: Call Bedrock (Beta)

on:
  pull_request:

jobs:
  call_bedrock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Call Bedrock (beta)
        run: |
          pip install boto3 --upgrade
          cd caip_03_02
          python run_bedrock.py